### PR TITLE
wf descriptions based on master dpl-workflow.sh

### PR DESCRIPTION
**Pull request by shahor02**

### CODE REVIEW

**Comment by davidrohr** [comment]
@shahor02 : I see that you do not set a couple  of default options for the `dpl-workflow.sh`, e.g.:
```
EXTINPUT=1 SYNCMODE=1 SHMSIZE=128000000000 EPNPIPELINES=1 SHMTHROW=0 INFOLOGGER_SEVERITY=warning
```

It is actually a bit annoying to repeat them in every line.
I would propose I add the possibility for common options in the parser, if there is a line
```
COMMON_OPTIONS: "..."
```
in the description file.
Then we can put stuff there and avoid to repeat it.
Does it make sense for you?

**Comment by shahor02** [comment]
I set EXTINPUT=1 in the https://github.com/shahor02/O2DataProcessing/blob/pr_updMW/testing/private/shahoian/run_ext_dpl.sh , for the rest I was relying on the defaults. 
Now I see  that the SYNCMODE=1 is actually not a default. 
Distributing too many overriddings to different places might be dangerous, I would prefer only the following hierarchy
lowest: defaults from setenv
middle: settings in the run.sh or its equivalent
highest: explicit env. vars in the workflow definition line.

For the cosmic and pp we should probably make the ITS_CONFIG_KEY empty.

**Comment by davidrohr** [comment]
@shahor02 : ok, but some defaults in the setenv are tuned for the laptop, not for the EPN.
I can change some based on the EPNMODE env variable which is set on the EPN, that should reduce the number of variables somewhat.

Yes, we should also introduce a setting beam_type, which comes from ecs, for pp, PbPb, cosmic, pPb. I'll do that, then we can adjust some settings accordingly.

I still believe a common option line in the workflow definition would make sense, but I'll check how it looks like after these changes.

**Comment by shahor02** [comment]
OK. In principle, most of params, like e.g. ITS_CONFIG_KEY, will eventually come from the CCDB.

**Pull request merged**
